language: node_js
node_js:
- node
git:
  depth: 10
branches:
  only:
  - master
script:
- npm run build
deploy:
  provider: gcs
  access_key_id: GOOGOXTPJ2JM4WHPFQXO
  secret_access_key:
    secure: BjepJ+4fPN+3PiEVZtZ97GHxu65qHAmdm1lQ26p8sOJZzjA6UJs1/M+8CJtj4KdKl/fyBn2aKhSlgJACjGDC/aQfEQiY8ERVwAf+agxkMwn3DRgzfThFT3qIs6OJptCAJBMcY/ntcBFRuXZQUsIPTfZjX9m1Y8uCnOUFMJM4ePjLocm7Y/8fMIJUnc+McQ0JvW8LqsQtUS40X2HsLbpiN3PxgFkrIvHoZLVDcHXxOdW3Vk7+81+K1uACFvM0mk5IlqqzjVqwlLiBAFcLXKGJAoW0uSh72h6N0ab4NsMrGmITVvagW9Rubh4yjabPoGBsRQpLni4jurBem80oaWyW8bdPzLUf8bpRaF1+gMgL+M4zcoO/BubKQvrkeGwNqAc5jbZZDgAfOP7xsmZf03/WiTXMAl2B8sw64kZmQSEHutwWJBxl5JfKB+ya+0Qbgr35RTmRy5iZgVd3SpzAiBb5mSNhMZ7K/Zo7b9XUNfdV6K0QsOOMumW8iipjG8KjT4bLwUfew13wqIC+OzMFWMYmSvLo2YaaRnvmwfV4LSWVTV1oV0cnWakFDtkMCSbuk1V63nORKWhs25cRiNQRSzSpgWVsrPGjFbJTpEo2JMZ4OUww5nCDLe/RhiUL8zzky+08p2R8135K4ZZS2pQXIx9jKCj9SwURKEqa/xT+LlGwd7E=
  bucket: santa.puppets.life
  local-dir: public
  overwrite: true
  acl: public-read
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: AquiGorka/santa.puppets.life
    branch: master
